### ISSUE TITLE
JavaScript SEP-0010 Client Reference Implementation

### ISSUE THREAD

**Issue by ElliotFriend** [tyvdh/stellar-quest-bounties#100]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/create-bounties.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [X] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

Pull Request #101

**Comment by tyvdh** [comment]
006b29eb3ccfd1a11410eb21320131241b828e7b2532890805d2440dd5a8c397
