### ISSUE TITLE
Add account viewer to an existing project

### ISSUE THREAD

**Issue by hanseartic** [tyvdh/stellar-quest-bounties#103]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/basic-account-viewer.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details
As per the [question in discord](https://discord.com/channels/763798356484161566/869565771586605136/874706680993161258) I am not completely sure if this submission is eligible. I just trust the reviewer's judgement as well as obviously the tallyman ;).

### Review this bounty
PR: hanseartic/stellar-claim#2
Deployed to: https://balances.lumens.space

**Comment by hanseartic** [comment]
To review navigate to the [PR's repo](https://github.com/hanseartic/stellar-claim/tree/add_account_overview) checkout the PR's branch and run `npm run start` in the checkout folder. You'll find the APP running on http://localhost:3000. 

Enter a stellar-account in the searchbar or use the Freighter-button.

When showing an account, that has open offers you'll also see those in the table:
![grafik](https://user-images.githubusercontent.com/1752217/129199313-0d993b80-0a0d-4d8e-a9fe-5aa8101a0491.png)

**Comment by tyvdh** [comment]
I think it is entirely viable, however the spec still needs to be followed and one of the criteria is a live site so reviewers don't need to pull, install or run anything.

![Screen Shot 2021-08-12 at 3 07 57 PM](https://user-images.githubusercontent.com/4383610/129254623-2e3c8eaf-2f79-4c7a-b4fb-ee57f48f6b34.png)

**Comment by tyvdh** [comment]
- https://vercel.com/dashboard
- https://surge.sh/
- https://codesandbox.io/
- https://stackblitz.com/

**Comment by hanseartic** [comment]
> I think it is entirely viable, however the spec still needs to be followed and one of the criteria is a live site so reviewers don't need to pull, install or run anything.
> 

Sorry. You're absolutely right. Added the link.

**Comment by tyvdh** [comment]
Looks good to me. Would love to get a couple more 👀  on it though.

We need to brainstorm surfacing reviewable tasks along with incentive / earn potential. To help push and advertise more reviewers. Maybe a GitHub Action tied to a unique page on the repo for building a table of all reviewable bounties along with earn potential. Could also do one for hunters to more quickly showcase bounty stats.

🤔

**Comment by hanseartic** [comment]
> To help push and advertise more reviewers. Maybe a GitHub Action tied to a unique page on the repo for building a table of all reviewable bounties along with earn potential. Could also do one for hunters to more quickly showcase bounty stats.

Sounds reasonable!

**Comment by ElliotFriend** [comment]
Looks quite nice! It was already a very useful app to get ahold of claimable balances, but it's really good to be able to see the assets I'm already holding. Great work! Looking at the code now.

As for surfacing reviewable submissions, I think the table kind of thing would be great! It's hard to know what submissions have already been "claimed" by reviewers. How can we make that kind of thing known to someone browsing the issues and/or PRs?

**Comment by ElliotFriend** [comment]
Looks well put together. The open offers displayed are a great touch, that I wouldn't have thought to include.

Also, enjoyed getting a chance to read through a real-life TypeScript app to get my head wrapped around it some more. Especially one that I didn't cobble together XD

Don't know how much weight I carry, but you've got stamp of approval!

👍

**Comment by tyvdh** [comment]
@hanseartic 2a10fb479a429a77415f65da011f48e61f769a0773015a9edbda32e789e81c5a
@ElliotFriend 2a10fb479a429a77415f65da011f48e61f769a0773015a9edbda32e789e81c5a
