### ISSUE TITLE
Video tutorials for Stellar-related subject

### ISSUE THREAD

**Issue by ralphilius** [tyvdh/stellar-quest-bounties#105]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/create-bounties.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [ ] 🟣&nbsp; Review completed

### Provide relevant details

Pull Request https://github.com/tyvdh/stellar-quest-bounties/pull/107

**Comment by tyvdh** [comment]
6ca67fb61146610184a163975de9e97ed0fe3f1074f24edc09bc024722e91247
