### ISSUE TITLE
Federation addresses for questers

### ISSUE THREAD

**Issue by hanseartic** [tyvdh/stellar-quest-bounties#110]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/create-bounties.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

PR: #109

### Discussed in https://github.com/tyvdh/stellar-quest-bounties/discussions/78

<div type='discussions-op-text'>

<sup>Originally posted by **hanseartic** August  5, 2021</sup>
# Scenario
Currently there are already a few different use-cases where a user's stellar-account is required. The most obvious ones: quests and bounties. But there is more like tip-bot, quest-monitor-bot.

So each time a quest-related service system is established there is need to map users (either discord or github) to stellar accounts. The federation-address would look like `<username>*quest.stellar.org` then.

It would be nice to provide questers with federation addresses for two reasons
* central place where addresses could be looked up
* foster community feeling (is this paying into this?)

# Bounty idea
The goal is to create come up with a bounty that addresses the scenario described above.

For example it could be to create a service that provides login via github or discord and allows users to add their stellar account. Said service could then act as source for a federation server (e.g. stellar's [reference implementation]) linked in https://quest.stellar.org/.well-known/stellar.toml.

## Useful links
- [federation] on stellar's developer docs
- lumenauts explaining [federated addresses]

[federation]: https://developers.stellar.org/docs/glossary/federation/
[federated addresses]: https://www.lumenauts.com/guides/what-are-federated-stellar-addresses
[reference implementation]: https://github.com/stellar/go/tree/master/services/federation</div>

**Comment by hanseartic** [comment]
@tyvdh : approved by @ElliotFriend

**Comment by tyvdh** [comment]
a374588bfeec077fafe7d9753bbe2edfa8b714d1deae337ec5594359b33b2f87
