### ISSUE TITLE
Stellar accounts as a service

### ISSUE THREAD

**Issue by rahimklaber** [tyvdh/stellar-quest-bounties#114]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/stellar-accounts-as-a-service.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

repo : https://github.com/rahimklaber/stellar-accounts-as-a-service

I'm a gonna try to implement it in kotlin.

hosted at : https://stellar-wallet.azurewebsites.net

**Comment by DieKautz** [comment]
I looked a bit into your endpoints and your api seems pretty sophisticated 😃

I don't know whether I covered every endpoint and result, but I found two oddities in the /pay endpoint

1. I might triggered a timeout on the /pay endpoint by trying to send less than a stroop to a valid account id.
2. By leaving exactly one stroop in my account I got "5.9604645E-8" as a balance from the /info endpoint and cannot send it to some other account
Maybe in correlation with that: when sending a significantly small amount compared to the balance it does not get less

ps: kotlin rocks 🚀

**Comment by rahimklaber** [comment]
@DieKautz  Thanks for the feedback.

It should work correctly now. Now, when sending less than a stroop you should get bad request.

Kotlin is awesome indeed.

**Comment by DieKautz** [comment]
It's fixed as far as I can tell.

The whole application seems very mature as part of this bounty.
I don't know whether its sensible to set no restrictions on usernames and passwords in production, but that shouldn't be a big problem here as this is just an API in in the deeper backend. (in production users would've already been created and handled elsewhere?)

#### Review criteria from bounty file

endpoints as stated in spec with valid JWT bearer auth

#### /register 
- [x] checking body fields
- [x] checking for already existing users 
- [ ] checking for sensible input     

#### /login 
 - [x] recognizing correct credentials
 - [x] checking body fields 

#### /info
 - [x] returning right users address and balance
 - [x] correctly showing external incoming funds
 - [x] validating JWT key

#### /pay
 - [x] successfully sending funds to external addresses
 - [x] successfully sending funds to other muxed accounts
 - [x] checking body fields [x] checking amount (>= 1 stroop & <= balance)
 - [x] validating JWT key 

Also password are getting stored hashed and avoiding SQL-Injections by using the DSL.

**Comment by rahimklaber** [comment]
@DieKautz  I agree with what you said about the usernames and passwords. I will change it. Thanks.

**Comment by rahimklaber** [comment]
@DieKautz  I finally got around to working on this again. On further thought I agree with you that this server probably shouldn't handle the registration/login. However, I did add a very simple username/password checker that can be extended to support more rigorous checking.

**Comment by LorDDark6660** [comment]
Link in description not working :
https://stellar-wallet.azurewebsites.net

**Comment by rahimklaber** [comment]
> Link in description not working :
https://stellar-wallet.azurewebsites.net

@LorDDark6660 only specific endpoints are accecible. Seems to work fine for me.

**Comment by tyvdh** [comment]
`559134a441c1251edbd37ae880455a1473a72b1af4d84e3c85f4aa8603fcf103`
