### ISSUE TITLE
Add Bounty: Claimable Balances in the Account Viewer

### ISSUE THREAD

**Issue by MatejMecka** [tyvdh/stellar-quest-bounties#116]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/create-bounties.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

https://github.com/tyvdh/stellar-quest-bounties/pull/115

**Comment by hanseartic** [comment]
@tyvdh  as you closed the PR (#115) could this then be moved to the next phase?
![grafik](https://user-images.githubusercontent.com/1752217/146314463-82f2d66d-2bb4-445c-98b2-472dfab53d27.png)

**Comment by tyvdh** [comment]
Yep!

**Comment by tyvdh** [comment]
`2fc601ce31b73c6dd1bf2de34995438ac743fcab143e1799ac33033b7d58cba1`
