### ISSUE TITLE
Basic account viewer implementation

### ISSUE THREAD

**Issue by tomkiljo** [tyvdh/stellar-quest-bounties#123]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/basic-account-viewer.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [X] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

Repository: https://github.com/tomkiljo/sqb-basic-account-viewer
Demo site: https://ny5k5mto.z6.web.core.windows.net/

**Comment by Smephite** [comment]
Looks good to me

Only thing to note :

In your readme you state

>Currently supported web wallets:
>
> * Albedo
> * Freighter
> * Albedo

But your demo only shows Albedo as an option

I'm not _that_ experienced with react but it looks allright. Maybe @hanseartic can step in?

**Comment by hanseartic** [comment]
From UX I am a bit confused about the links to laboratory because they are not specific. Did you mean to link to stellar.expert?

**Comment by tomkiljo** [comment]
All three web wallets are supported but Freighter and Rabet (typo in readme says Albedo, to be fixed) are shown only if they are enabled in the users browser (filtered [here](https://github.com/tomkiljo/sqb-basic-account-viewer/blob/df68337d3e8f044a76fe6b3a9e0313891f959b21/src/components/WalletModal.tsx#L100)). Attached a screenshot from my browser with all three enabled.

![image](https://user-images.githubusercontent.com/11896368/132720456-17958488-6ea7-4e0f-9135-2de1af5d05be.png)

Linking to laboratory seems to break occasionally for some reason, I'll change them to point to stellar.expert  :+1:

**Comment by tomkiljo** [comment]
Updated the readme and the links to point to stellar.expert. Changes pushed to repo, demo site updated as well.

**Comment by hanseartic** [comment]
> All three web wallets are supported but Freighter and Rabet (typo in readme says Albedo, to be fixed) are shown only if they are enabled in the users browser (filtered [here](https://github.com/tomkiljo/sqb-basic-account-viewer/blob/df68337d3e8f044a76fe6b3a9e0313891f959b21/src/components/WalletModal.tsx#L100)). Attached a screenshot from my browser with all three enabled.

Alright, got it. What do you think about hinting the user which ones can be uses by having disabled state?
<img width="274" alt="grafik" src="https://user-images.githubusercontent.com/1752217/132751777-12d712b5-290e-4aac-82b8-c1c7202ef95e.png">

**Comment by tomkiljo** [comment]
Many thanks for your comments and insights, great stuff about the operations and balances to keepi in mind for future :+1:

I've updated the wallet selection to include all three wallets and display notification for unavailable wallets.
![Screenshot from 2021-09-10 13-07-23](https://user-images.githubusercontent.com/11896368/132839736-c20c4c1d-8972-46ab-ba62-76621c4fa7a7.png)

Updated the logic for retrieving the account creation operation starting from the first transaction.

On UI side kept it simple and only added a few characters to the account shortened id. UI is by far my greatest weakness :joy: 

Repo and demo site updated, added demo site link to repo description.

**Comment by tomkiljo** [comment]
@Smephite @hanseartic , any other comments/requirements, or is it ok to mark the bounty as review completed? Already eyeballing next bounty the hunt 😄

**Comment by hanseartic** [comment]
> @Smephite @hanseartic , any other comments/requirements, or is it ok to mark the bounty as review completed? Already eyeballing next bounty the hunt 😄

🏁 from my side. really nice first controbution 👏🏼

**Comment by Smephite** [comment]
> > @Smephite @hanseartic , any other comments/requirements, or is it ok to mark the bounty as review completed? Already eyeballing next bounty the hunt 😄
> 
> 🏁 from my side. really nice first contribution 👏🏼

+1 from me as well! Good job! Looking forward to seeing more submissions from your end :)

**Comment by tomkiljo** [comment]
Thank you both :partying_face:

**Comment by tyvdh** [comment]
`15e2fb458e4f5df9806d96f70f1a5c68d3d8345271c98e75fe54a1a7e5b7da2f`
