### ISSUE TITLE
Stellar Accounts as a Service

### ISSUE THREAD

**Issue by tomkiljo** [tyvdh/stellar-quest-bounties#125]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/stellar-accounts-as-a-service.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

GitHub repo: https://github.com/tomkiljo/stellar-accounts-as-a-service

**Comment by tomkiljo** [comment]
Demo installation for the service available in:
- API endpoint: https://func-1ab85fe6.azurewebsites.net/api
- Relay status: https://app-1ab85fe6.azurewebsites.net

Missing some sanity checks from at least the `/pay` endpoint, to be updated.

**Comment by tomkiljo** [comment]
Feels like ready for a review round. A bunch of the database level payment logic is done with stored procedures so it's worth while checking out the [schema](https://github.com/tomkiljo/stellar-accounts-as-a-service/blob/main/db/schema.sql).

**Comment by hanseartic** [comment]
Thank you for your submission! As you may have noted it's a bit quiet around here. Still you did not go unnoticed. Bear with us and thank you for your patience.

**Comment by rahimklaber** [comment]
I had a look and It seems like the `/info` endpoint doesn't update when a user receives XLM. I checked the relay status page, and it seems to have processed the transaction, but it `info` endpoint is not updated.

This is the address I sent XLM to : `MAMLLORKHRKYR2ODW23RKFBGXSMZLDOGUZEKN5WULD7CLUVPMGSPIAAAAAAAAAAANQYFM`

**Comment by tomkiljo** [comment]
Thanks for the comment @rahimklaber. I checked it out and had there was a bug in the db schema where stored procedure parameters should have been BIGINT instead of INT. Fixed the schema and restarted the relay and I can see the deposit is now handled correctly. See the [commit](https://github.com/tomkiljo/stellar-accounts-as-a-service/commit/62a604bbb4a1547a83c563ef5c9dba1a0f7919e0) for more details.

**Comment by rahimklaber** [comment]
Alright, I think I've checked everything. Everything seems to be fine except for two things:
- If two users try to pay using the service at the same time, one request will succeed while the other one will return a `500` response code.
- Sending payments to muxed accounts results in a `404`.

**Comment by tomkiljo** [comment]
@rahimklaber I've created a fix for the issues you encountered in this [commit](https://github.com/tomkiljo/stellar-accounts-as-a-service/commit/92b472fb7ac5dfbf4705533999bc4698af71fd81). Demo environment updated.

> If two users try to pay using the service at the same time, one request will succeed while the other one will return a 500 response code.

Sequential payment operations from the custodian account are now forced by a pessimistic payment lock. Underneath utilizing Azure Blob Storage lease mechanism for this. If the lock is not acquired in a timely fashion (~15 seconds) the request fails with a 504 status code. Not a "production" grade solution but I think it will do here :)

> Sending payments to muxed accounts results in a 404.

Muxed target account handling was just messed up, should be ok now.

**Comment by tyvdh** [comment]
Any chance you could stand this back up? https://func-1ab85fe6.azurewebsites.net/api seems to be 💀

**Comment by tomkiljo** [comment]
It's back up, my custodian account was gone due to testnet reset :smile:

**Comment by tyvdh** [comment]
@tomkiljo 
![Screen Shot 2021-12-15 at 12 57 29 PM](https://user-images.githubusercontent.com/4383610/146239931-fb7de9e7-3a7f-4570-bbb5-0b515fb3dd0c.png)

**Comment by tomkiljo** [comment]
@tyvdh the api root doesn't return anything, https://func-1ab85fe6.azurewebsites.net/api/[register,login,info,pay] endpoints have handlers as defined in the spec.

**Comment by tyvdh** [comment]
I'm dumb haha. Working fine now. So I'm able to get all the way to /info where the balance is `0` but when I use laboratory to pay the muxed address the balance is still 0. Is this expected? How can I get into a state able to make a payment from the muxed address?

**Comment by tomkiljo** [comment]
Had to restart the relay that's listening for custodial account transactions, it had died probably due to testnet reset :smile: I see the payment is now processed and should show up in `/info`

**Comment by tyvdh** [comment]
`08aa497344ba08ff0546bcd4f2417bc21a287c463e6d752fdf462422a84a6111`
