### ISSUE TITLE
Basic Account Viewer by fpbrault

### ISSUE THREAD

**Issue by fpbrault** [tyvdh/stellar-quest-bounties#128]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/basic-account-viewer.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

Repo: https://github.com/fpbrault/stellar-basic-account-viewer

Demo: https://stellar-basic-account-viewer.vercel.app

**Comment by raeesnazeer** [comment]
That looks neat!

Everything seems to be working fine and passes all the requirements of the bounty.

You consider adding a message for Rabet and freighter if it's unavailable something like the below example, else feels like it's not working.
![image](https://user-images.githubusercontent.com/8734009/135278844-7a3fe812-310a-44b3-bfb5-cf9daa0b46b8.png)

Rest everything 🟢 from my side.

**Comment by fpbrault** [comment]
I made the change, buttons will now be disabled and hovering over them shows a small message. Due to how Rabet and Next.js work, I had to add a small delay before the wallet check.

**Comment by raeesnazeer** [comment]
Good job! 

The review is completed from my end. Looking forward to more submissions!

**Comment by tyvdh** [comment]
`89b34e363e44161016b99b04e1639ff6b3dfe37e2ec67edb903ed0e7d775764a`
