### ISSUE TITLE
Basic Account Viewer by boonku

### ISSUE THREAD

**Issue by boonku** [tyvdh/stellar-quest-bounties#133]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/basic-account-viewer.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [X] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

Repository: https://github.com/boonku/boonku.github.io

Demo: https://boonku.github.io

**Comment by raeesnazeer** [comment]
Hello,

Looks good, but why have you disabled the Freighter and Rabet buttons?

**Comment by Kanaye** [comment]
> Looks good, but why have you disabled the Freighter and Rabet buttons?

Take a look at the codebase: 
https://github.com/boonku/boonku.github.io/blob/6f53daa214ba91aeeb1dd71f1cd3b52c4ced6dd2/active-buttons.js#L1-L6
the buttons are disabled, when the extensions aren't installed/available, which makes sense imho.

**Comment by raeesnazeer** [comment]
> > Looks good, but why have you disabled the Freighter and Rabet buttons?
> 
> Take a look at the codebase: https://github.com/boonku/boonku.github.io/blob/6f53daa214ba91aeeb1dd71f1cd3b52c4ced6dd2/active-buttons.js#L1-L6 the buttons are disabled, when the extensions aren't installed/available, which makes sense imho.

![image](https://user-images.githubusercontent.com/8734009/136039076-22b875dd-7094-4338-8d50-680311e2eec1.png)
I have the rabet extension installed, but it still remains disabled.

**Comment by boonku** [comment]
It should be working now. I have also added tooltips for buttons to show why they are disabled.

**Comment by raeesnazeer** [comment]
> It should be working now. I have also added tooltips for buttons to show why they are disabled.

Yes, it's perfect now!

Good job! The review is completed from my end. Looking forward to more submissions!

**Comment by boonku** [comment]
Thanks

**Comment by tyvdh** [comment]
`2c912df8971be87c9b1c0edb42ed632318015d1ae9b9e580869a53749a7222ff`
