### ISSUE TITLE
Basic Account Viewer by Rachanashenoy20

### ISSUE THREAD

**Issue by Rachanashenoy20** [tyvdh/stellar-quest-bounties#148]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/basic-account-viewer.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [X] 🟢&nbsp; Ready for review
- [ ] 🟣&nbsp; Review completed

### Provide relevant details

Repo: https://github.com/Rachanashenoy20/stellarquest-bounties/tree/main

Demo: https://rachanashenoy20.github.io/stellarquest-bounties/

**Comment by raeesnazeer** [comment]
Hello!

Everything looks good and working as intended. The review is completed.

**Comment by DieKautz** [comment]
When comparing your submission to the one by @sohanrai #147, there appears to be a lot of similarities: [diff of index.html](https://www.diffchecker.com/7hya5zU2)

As he is the one with the earlier timestamps, I suspect you took some inspiration from him without putting extensive own work into building it yourself.

/request for close @tyvdh
