### ISSUE TITLE
Basic Account Viewer by vinamogit

### ISSUE THREAD

**Issue by vinamogit** [tyvdh/stellar-quest-bounties#150]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/basic-account-viewer.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [X] 🟢&nbsp; Ready for review
- [X] 🟣&nbsp; Review completed

### Provide relevant details

Github repository: [https://github.com/vinamogit/stellar-account-viewer](https://github.com/vinamogit/stellar-account-viewer)

Demo: [https://vinamogit.github.io/stellar-account-viewer/](https://vinamogit.github.io/stellar-account-viewer/)

**Comment by raeesnazeer** [comment]
Hello,

Very nicely done, loved the chart representation and display of balance with icons!

The only issue I see is the freighter button doesn't respond if the extension is not installed, so it's better to add a check for that and notify users to install it. 

Rest everything is perfect and lovely. Once you fix the freighter issue you can mark is review completed from my end.

Excellent Job!

**Comment by vinamogit** [comment]
Hello,

Thank you for the feedback.
I will fix that soon.

**Comment by vinamogit** [comment]
Bug fixed.

**Comment by vinamogit** [comment]
Done. Thank you.

**Comment by tyvdh** [comment]
`f46a4b3bb22f784a4ba5effc10639fe358c182294d3ec8e3bffc7fd478c4e649`

**Comment by vinamogit** [comment]
Confirm. Is it ok if I send it back to the source account @tyvdh ?

**Comment by tyvdh** [comment]
`fa38180928b2d1d196e364aab25cd912064e6d2b29e012c60a40842c21de98c2`

**Comment by vinamogit** [comment]
ed53d20b214cd8f68366ef1dd1644a97a4a676511b06dd4efdfd9b63476d548e
