### ISSUE TITLE
basic-account-viewer by orsab

### ISSUE THREAD

**Issue by orsab** [tyvdh/stellar-quest-bounties#153]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/basic-account-viewer.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [X] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

Repo: https://github.com/orsab/stellar-bounty-l1
Demo: https://orsab.github.io/stellar-bounty-l1

**Comment by raeesnazeer** [comment]
Hello,

Nice work, all the bounty requirements are fulfilled and working as expected.

The review is completed from my end.

**Comment by orsab** [comment]
Thanks @raeesnazeer

**Comment by LorDDark6660** [comment]
Everithing works pretty fine for me...

**Comment by tyvdh** [comment]
> only gripe i have is the tsconfig is set to "emitdeclarationsonly: true" but also "noemit: true" however this issue is almost negligible.

I am here for this level of review 🤣

**Comment by ElliotFriend** [comment]
`7e009f2768ca6f902aa2dae852df1ee57923528a4a56e42026b5d0d0024a1d92`

**Comment by ElliotFriend** [comment]
@orsab For accounting purposes, what's your Discord user id? If you'd rather not share that here, you can send me a DM on discord.

**Comment by orsab** [comment]
Hi @ElliotFriend, my nickname in discord is orsab, like there. Does stellar community have channel in discord?

**Comment by ElliotFriend** [comment]
> Hi @ElliotFriend, my nickname in discord is orsab, like there. Does stellar community have channel in discord? 

Yes, we do! There are a few, but the relevant one for these bounties is "Stellar Quest." You should totally come join us!

https://discord.gg/3dRWymya
