### ISSUE TITLE
stellar-accounts-as-a-service by orsab

### ISSUE THREAD

**Issue by orsab** [tyvdh/stellar-quest-bounties#154]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/stellar-accounts-as-a-service.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

**Comment by orsab** [comment]
Repo:  https://github.com/orsab/stellar-bounty-l2
Demo Endpoint: https://stellar-bounty-l2.oralkin.repl.co

**Comment by LorDDark6660** [comment]
I am missing in description that i have to rename example file to .example.env

![IMG_20220129_085004](https://user-images.githubusercontent.com/92062140/151652958-8857792b-d4ee-406c-898a-539358dc629a.jpg)

**Comment by orsab** [comment]
Hi, you have explanation into the README.md,
https://github.com/orsab/stellar-bounty-l2#mv-envexample-env

**Comment by orsab** [comment]
In repl you have to click on the start button only, if you trying it
locally, move .example.env into .env

**Comment by orsab** [comment]
Hi @DieKautz, thank you for your code review. Just fixed some bugs like: error show, floating point...
I'm not antagonist, as a result, I'm not pressure users to create good usernames. Sometimes crazy username with unicode is very good practice in security 😉

**Comment by ElliotFriend** [comment]
`c6dfd6696fa140475f15fc03e759408a4e0a70faf6f1184899996bc5993d8a2b`
