### ISSUE TITLE
New bounty for Fee Stats in Lab Endpoint Explorer

### ISSUE THREAD

**Issue by w00kie** [tyvdh/stellar-quest-bounties#155]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/create-bounties.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

As requested by @tyvdh, we should have a bounty for someone to make a PR for adding missing Horizon endpoints, e.g. the Fee Stats endpoint, to the Lab's Endpoint Explorer.

PR: https://github.com/tyvdh/stellar-quest-bounties/pull/156

**Comment by tyvdh** [comment]
Probably a separate bounty but worth looking into. I'm not sure the fee isn't already automatically calculated. I know it's not always 100, I just don't know what the calculation / logic is atm

**Comment by tyvdh** [comment]
> I like this idea. I would really like to have an automatic fee estimator for times that surge pricing is in effect on the 'create-transactions' page.

Probably a separate bounty but worth looking into. I'm not sure the fee isn't already automatically calculated. I know it's not always 100, I just don't know what the calculation / logic is atm

**Comment by silence48** [comment]
> > I like this idea. I would really like to have an automatic fee estimator for times that surge pricing is in effect on the 'create-transactions' page.
> 
> Probably a separate bounty but worth looking into. I'm not sure the fee isn't already automatically calculated. I know it's not always 100, I just don't know what the calculation / logic is atm

It has always shown 100 for me even during surge pricing times; i will try to check on it.

**Comment by Kanaye** [comment]
> It has always shown 100 for me even during surge pricing times; i will try to check on it.

https://github.com/stellar/laboratory/blob/5dfac1ccea143fe1c7aeb24471df08851e455932/src/actions/transactionBuilder.js#L101-L117 that's were they fetch it (used via the store from the [transaction builder](https://github.com/stellar/laboratory/blob/5dfac1ccea143fe1c7aeb24471df08851e455932/src/views/TransactionBuilder.js)) ;)

**Comment by w00kie** [comment]
@tyvdh, fyi I did not put a bounty amount as I thought that should be left to you.

**Comment by tyvdh** [comment]
Pretty low, this one should be quite simple as far as a PR is concerned. Let's shoot for 300 XLM and see if anyone takes it.

**Comment by ElliotFriend** [comment]
`7fce11ebde2fce95300a4105a01e786bfa184867d226589e45f0476e058affa8`
