### ISSUE TITLE
TipBot

### ISSUE THREAD

**Issue by MatejMecka** [tyvdh/stellar-quest-bounties#165]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/create-bounties.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [X] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

PR #2

**Comment by BlackBadPinguin** [comment]
This already looks good to go, so I think you could change the review label to Review completed/reward.

**Comment by LorDDark6660** [comment]
Its OK...great work 👍

**Comment by silence48** [comment]
https://github.com/tyvdh/stellar-quest-bounties/blob/99f45312ccb45be29270afaa563ea64c52795649/bounties/level-2/tipbot.md

This is the bounty he made and it looks good to me i think, but maybe the bounty should be 2k xlm?

**Comment by ElliotFriend** [comment]
`7c0d569395f95a3f6e6264f38009525163232616fdf8bad8b9c24aea1cc0c817`
