### ISSUE TITLE
SEP-10 implementation by orsab

### ISSUE THREAD

**Issue by orsab** [tyvdh/stellar-quest-bounties#169]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/sep10-javascript-server.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [X] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

REPO: https://github.com/orsab/stellar-bounty-l2-sep10
Demo on Repl.it: https://replit.com/@OrAlkin/stellar-bounty-l2-sep10

**Comment by DFugere1** [comment]
Hi,

Nice implementation of SEP-0010 server.


**_Testing the solution:_**
I tested your implementation of SEP-0010 with the Rabet Wallet, the implementation always return the Rabet wallet with network as the Main Network. 

When testing I could authenticate using the server implementation and I received my JWT auth bearer Token.

**_Testing the API_**
Everything worked fine when using correctly. 

When using incorrectly:
  - The Connect Button, does nothing if already connected, not an issue, but not user friendly.
  - The Send Button does noting if not connected, not an issue, but we could add a note saying to connect using the Rabet Wallet.
  - The Sign and Request action both return message if used improperly.

**_Validating the JWT_** 
The JWT seem relevant and complete, it contain a header, a payload containing information for the Issuer, subject, issued time and expiration time and the signature.

**_Authentication Flow_**
There is one step from the stellar-protocol I can't seem to validate, how do you confirm the signature is correct for the Client Account? (Step 15)

**Comment by BlackBadPinguin** [comment]
Overall nice Submission!

I tested the Implementation of your API and it looks good, everything seems according to spec. Also, the use of muxed Accounts does not produce any Errors which is good. The Authentication Flow works fine, apart from Step 15 as already mentioned in the issue from @DFugere1. However, the JWT is good. I tested it with the JS SDK.

**Comment by orsab** [comment]
Hi @DFugere1 , @BlackBadPinguin . Thank you for yours code review, just fixed some bugs you mentioned me, like: signatures check, UX improvements and some bugs with Rabet wallet on testnet.

**Comment by ElliotFriend** [comment]
`2083a0a677111a86e8d429b76786559d765834bcb8d47eb2d66a889bdce9a544`
