### ISSUE TITLE
Tip bot by orsab

### ISSUE THREAD

**Issue by orsab** [tyvdh/stellar-quest-bounties#177]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/tipbot.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

Repo: https://github.com/orsab/stellar-bounty-tipbot
Demo: https://discord.gg/eBQMcwkhPx

Started with tip-bot, also I consider to change some logic for more usability:
1. Create addition role 'Sponsor' with ability to tip members
2. Only Admin can add role 'Sponsor'
3. Sponsors can use custodian wallet to pay the members with BEAR token
4. Available types to tip: 
- by slash command, like: '/tip amount:50 user:@orsab'
- by reacting the message with emojis specified in the bounty
5. If member not have the Stellar account - will be DM message with instructions how to create. Lobstr by default
6. If member don't have the trustline - custodian account will send Claimable Balance with BEAR token and notify the member in DM
7. Ability link Stellar account by slash command '/link GJSH...'

**Comment by LorDDark6660** [comment]
Great job, I haven't discovered any bugs yet, I'll test all the features tonight.

**Comment by orsab** [comment]
Hi, let me know if you have any questions or bugs to report.

**Comment by silence48** [comment]
Hey I didn't notice this! I am going to try it out tonight will let you know any input!

**Comment by orsab** [comment]
Hi, updated the code now. 
* For test reasons added ability to everyone become a Sponsor by calling ```/sponsor``` command
* Demo added: https://discord.gg/eBQMcwkhPx
- Don't forget link the member before tip.
- All notifications by bot are inside the private manages, because ephemeral messages are delete automatically after some time.

**Comment by orsab** [comment]
Updated issuer account and issue script, some bugs are fixed too

@silence48 @LorDDark6660

**Comment by LorDDark6660** [comment]
I just tested the demo and everything works as it should, I joined as a sponsor, linked stellar address, I sent a tip and a claim BEER CB, for me 👍

**Comment by orsab** [comment]
@ElliotFriend Hi, when this bounty can be closed?

**Comment by silence48** [comment]
I tested in discord and it seemed to work as intended!

**Comment by ElliotFriend** [comment]
Hey, everyone!

Sorry for the delay on this one. Finally got your payouts processed!

`bac1ba1b2f7527f903c5f908418a78e88b90d5cd0723138745f87b2a331679af`

Thanks for the hard work and dilligence! @orsab @LorDDark6660 @silence48
