### ISSUE TITLE
review stellar-lab-albedo

### ISSUE THREAD

**Issue by ralphilius** [tyvdh/stellar-quest-bounties#21]
PR https://github.com/stellar/laboratory/pull/546 for bounty #11

**Comment by Kanaye** [comment]
Not sure that it is the greatest idea to open up PRs on the origin repo before we  had a chance to review tbh. But well to late, I'll take a look.

**Comment by Kanaye** [comment]
I guess you've missed a `console.log` statement from "debugging"  https://github.com/stellar/laboratory/pull/546/files#diff-00c0965499c0df35abe501fc79e1b295a7daef567e5b6fdd9f83d7a5654db8feR49

**Comment by ralphilius** [comment]
> I guess you've missed a `console.log` statement from "debugging" https://github.com/stellar/laboratory/pull/546/files#diff-00c0965499c0df35abe501fc79e1b295a7daef567e5b6fdd9f83d7a5654db8feR49

Yeah.. I missed that. They don't have eslint though 😃

**Comment by apaldiwal** [comment]
Can you change 'Albedo' label with 'Wallet' or something similar? I know Albedo isn't exactly a wallet, but it will be good to have a generic label.

![image](https://user-images.githubusercontent.com/73634107/127546381-3261c457-c2bb-4294-924b-787446a7e839.png)

**Comment by tyvdh** [comment]
> 1. Can you change 'Albedo' label with 'Wallet' or something similar? I know Albedo isn't technically a wallet, but it will be good to have a generic label.
> 2. When I click the 'Sign with Albedo' button - can it switch over to a new tab instead of opening a pop up?
> 
> ![image](https://user-images.githubusercontent.com/73634107/127546381-3261c457-c2bb-4294-924b-787446a7e839.png)

Albedo makes sense as it matches the current pattern with Freighter
![Screen Shot 2021-07-29 at 2 55 49 PM](https://user-images.githubusercontent.com/4383610/127550044-aac340d9-9ac7-4775-829f-1b80571bf399.png)

**Comment by apaldiwal** [comment]
> > 1. Can you change 'Albedo' label with 'Wallet' or something similar? I know Albedo isn't technically a wallet, but it will be good to have a generic label.
> > 2. When I click the 'Sign with Albedo' button - can it switch over to a new tab instead of opening a pop up?
> > 
> > ![image](https://user-images.githubusercontent.com/73634107/127546381-3261c457-c2bb-4294-924b-787446a7e839.png)
> 
> Albedo makes sense as it matches the current pattern with Freighter
> ![Screen Shot 2021-07-29 at 2 55 49 PM](https://user-images.githubusercontent.com/4383610/127550044-aac340d9-9ac7-4775-829f-1b80571bf399.png)

I was just thinking if we end up adding support for more wallets, the UI will get cluttered. But yeah, it makes sense to to match the current pattern.

**Comment by Kanaye** [comment]
Looks good to me! I'd personally replace some of the `if-else-if-else-if`-statments with switch-statements ... but well they are used that way in other function too, so they kinda belong into the codebase. Also tested the functionallity and other than albedos sometimes weird UI I didn't notice anything 👍

**Comment by ralphilius** [comment]
> > > 1. Can you change 'Albedo' label with 'Wallet' or something similar? I know Albedo isn't technically a wallet, but it will be good to have a generic label.
> > > 2. When I click the 'Sign with Albedo' button - can it switch over to a new tab instead of opening a pop up?
> > > 
> > > ![image](https://user-images.githubusercontent.com/73634107/127546381-3261c457-c2bb-4294-924b-787446a7e839.png)
> > 
> > 
> > Albedo makes sense as it matches the current pattern with Freighter
> > ![Screen Shot 2021-07-29 at 2 55 49 PM](https://user-images.githubusercontent.com/4383610/127550044-aac340d9-9ac7-4775-829f-1b80571bf399.png)
> 
> I was just thinking if we end up adding support for more wallets, the UI will get cluttered. But yeah, it makes sense to to match the current pattern.

That's what I originally did until I thought Software Wallets is not a good name, so I sticked with current implementation until we have more integration.

**Comment by tyvdh** [comment]
@Kanaye 
@apaldiwal 
Should we consider this bounty complete and ready for payout then? I don't think waiting on PR acceptance in this case is reasonable as the Lab team tends to move slowly.

**Comment by Kanaye** [comment]
> Should we consider this bounty complete and ready for payout then? I don't think waiting on PR acceptance in this case is reasonable as the Lab team tends to move slowly.

Maybe we should think about how we handle this in future.  "External" (aka. non-lumenaut) hunters might lose interest on bounties once they've been payed out and don't have interest in resolving issues/feedback from the upstream repository. So maybe we should split bounties with upstream respository to "X XLM for completing the bounty and Y XLM the upstream PR gets merged" or something like that. 
But I think we're fine here and can consider this bounty completed 👍

**Comment by tyvdh** [comment]
@apaldiwal and @ralphilius can you add your addresses to PRs on this file?
https://github.com/tyvdh/stellar-quest-bounties/blob/main/ADDRESSES.yaml

Thanks!

**Comment by apaldiwal** [comment]
> > Should we consider this bounty complete and ready for payout then? I don't think waiting on PR acceptance in this case is reasonable as the Lab team tends to move slowly.
> 
> Maybe we should think about how we handle this in future. "External" (aka. non-lumenaut) hunters might lose interest on bounties once they've been payed out and don't have interest in resolving issues/feedback from the upstream repository. So maybe we should split bounties with upstream respositories to "X XLM for completing the bounty and Y XLM when the upstream PR gets merged" or something like that.
> But I think we're fine here and can consider this bounty completed 👍

I really like this idea!

**Comment by tyvdh** [comment]
@ralphilius 48f6df792348da83b7d09cd93b6c239ecfe29f5022b189129533768337ad3695
@Kanaye 803759f86cc13edf7552afe22fc6149050c088fb007c701a47a113f64a8b8b3f
@apaldiwal 327e519f0bd70e94b9ddc4e48b6576a762c2c2a8a33048b54edee6b996fefc1e
