### ISSUE TITLE
stellar-quest-badge-checker.md

### ISSUE THREAD

**Issue by tyvdh** [tyvdh/stellar-quest-bounties#4]
https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/stellar-quest-badge-checker.md

**Comment by rahimklaber** [comment]
started working here: https://github.com/rahimklaber/stellar_quest_badge_checker.

Maybe we should require people to add a comment like this in the future to see who is working on what and to avoid more people than necessary to work on one thing?

**Comment by ElliotFriend** [comment]
Oooh, oooh! Me too 😆 

https://github.com/ElliotFriend/sq-badge-checker

**Comment by tyvdh** [comment]
Once you have a repo ready for review don't forget to add it as a new Issue. Excited to see what you come up with!

**Comment by rahimklaber** [comment]
submission : https://github.com/tyvdh/stellar-quest-bounties/issues/23

**Comment by tyvdh** [comment]
As this issue doesn't follow the existing pattern I'm going to close it. If you are currently working on an implementation you should open a new issue for tracking your specific implementation of this bounty if you haven't already.
