### ISSUE TITLE
🔵 bounty-template.md

### ISSUE THREAD

**Issue by tyvdh** [tyvdh/stellar-quest-bounties#40]
Here's my proposal for a bounty template. Let's use this to work off of to arrive at the perfect bounty template.

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/README.md

**Comment by Smephite** [comment]
We need to have "" in the context link.
without: https://github.com/tyvdh/stellar-quest-bounties/issues?q=create-bounties
with: https://github.com/tyvdh/stellar-quest-bounties/issues?q=%22create-bounties%22
