### ISSUE TITLE
Stellar Quest badge checker

### ISSUE THREAD

**Issue by ElliotFriend** [tyvdh/stellar-quest-bounties#41]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/stellar-quest-badge-checker.md

### Mark your progress

- [x] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

I've been working on this bounty for a bit.

Here's the GH repo: https://github.com/ElliotFriend/sq-badge-checker

And here's a live site: https://badges.elliotfriend.com

## Here's the basic idea:

- You login with your albedo account, and your badges show up, alongside some details from the transaction.
- You can export your badges (customized by a filter) into an image which has some verification data hidden in it with steganography.
- The verification is essentially the opposite. Someone uploads the image file, and the app extracts the data and verifies the signature.

## Particular Areas of Concern and Questions for Reviewers

- I'm pretty new to React, and I'm **quite sure** I've built this in a clumsy way. I've managed to make things work, but what would likely be different if I were a react pro?
- The steganography idea seems nice to me on first blush, but the compute power required by a client may make this an unrealistic approach. Plus, if the data could be damaged when uploading to website/emails/etc. (still testing that) it could defeat the whole purpose.
- If I'm depending on an image to do the verification, what's to keep someone from photoshopping their own image to fake that they own all the badges?

**Comment by tyvdh** [comment]
ftr this is a great Issue example. Well done!

**Comment by tyvdh** [comment]
However if you're ready for review the status should be 🟢  so reviewers know it's their time to shine. If you're not ready yet though 👍

**Comment by ElliotFriend** [comment]
Also, ftr facebook **immediately** screwed up my whole steganography scheme... 👎🏻 

Really wished I had tried that much earlier in the process!!! 😠 

Yeah, not quite ready yet Hehehe

**Comment by Kanaye** [comment]
> If I'm depending on an image to do the verification, what's to keep someone from photoshopping their own image to fake that they own all the badges?

You shouldn't "trust" the input from a user. You should verify that the signature matches and that the account has all the badges at time of verification.

**Comment by ElliotFriend** [comment]
Yeah. Yeah, I think I'm seeing it now.

I think I was depending too much on encapsulating all the verification at time of "export" and essentially just reading that back in to "verify." It seems so obvious now that wouldn't cut it. You phrased that just right, Kanaye, to rattle things in my brain into the right position. Thanks!

**Comment by Kanaye** [comment]
![grafik](https://user-images.githubusercontent.com/5108989/127916216-992d977f-661e-4928-97e8-6e3af1e5b7f4.png)
That image (the colored version with a greyed out, monochrome version below) confused me at first glance. I'd add some overlay onto the disabled/greyed out version like "SQ0101 Monochrome: You don't own this badge" to make it easier for a user to grasp what that's all about.

Also the font-size seems really small, especially with the  low contrast  with grey font on grey background in the "Date Earned" section.

On my hardware I generate a "proof image" in about 20 seconds, FF asks me if I want to kill the page and well ... my CPU starts burning ... but it works. 
Decoding/Verifing the proof seems not to work on the version live at badges.elliotfriend.com at the time of writing this. Neither chrome nor firefox do anything when clicking that button 🤔 So haven't tested that yet.

Next I'll look at the codebase, but wanted to give you first feedback. And I really like the design, besides the thing(s) mentioned earlier.

**Comment by ElliotFriend** [comment]
Thanks a bunch! I'll work on those aspects you mentioned. Verify doesn't do anything yet.

**Comment by ElliotFriend** [comment]
Tonight, I moved a bunch of stuff around, and I think got the app into a more "suitable" form 🤞🏻 

Also, for the verification, I'm thinking I could make a long hex-encoded string that decodes to a JSON.stringify-ed object containing the pubkey, signed message, asset codes, and operation ids for those asset payments to verify and check when someone visits `badges.elliotfriend.com/verify/:hexstring` That hex string could then be shared/copied-pasted/qr-coded/etc.

Any thoughts on that direction?

**Comment by Kanaye** [comment]
if you've got the operation ids (or tx-hashs), you can lookup the asset codes and don't need to store them with the json, also I'd just hash the object and store its hgash along with it on an other object (or something else an array e.g. `[{I: "am the object"}, "Hash here!"]` or something). 
Just a note: The generation of operation ids isn't specified anywhere but is something the horizon devs came up with just as a paging token. So while it *very* unlikely, it maxy change in future, so I'd just stick with tx-hashs, but they are larger and therefore may not work if you need to urlencode them.
Also it's probably better if you encode the object in url-safe base64 instead of HEX as the url will probably be very long in hex and therefore might not be usable in all browsers.

**Comment by apaldiwal** [comment]
I really like the UI for the website! I just have a minor issue for now, the logout button is a little bit weird. 
Can we have the button label as 'logout' instead of an abbreviated public key?
![image](https://user-images.githubusercontent.com/73634107/128375003-d944a0e6-1e9a-479d-a444-af7b38b860af.png)

P.S. I have only started looking at the website, I'll have more reviews as I look through it. Oh, and good job!

**Comment by ElliotFriend** [comment]
Thanks for the kind words! I agree it is confusing. I'll figure out something better for it.

Thanks!

**Comment by apaldiwal** [comment]
I feel the quest description can be removed from the badges. It will make the badges more compact and honestly I am not sure if it is needed. It's just what I think, you don't have to change it :)

![image](https://user-images.githubusercontent.com/73634107/128379545-23694813-eef6-4d44-a52b-4dfe822c3b9f.png)

**Comment by ElliotFriend** [comment]
I think I like having them. I was almost thinking of, like, Pokemon cards (or what-have-you), and thinking about information that I could include in that direction. I could make it one of the filterable things, though.

On a related note, the cards will display how much xlm you earned as a prize for the quest, if you earned any. But, that stuff doesn't show up right away. If you're looking at them, and you change one of the filters, that information will show up in the re-render.

Probably something to do with the async fetch to the horizon endpoint.

Technically speaking, I'm not sure how to fix that. I'm looking into it, but if anyone knows off the top of their head, I'm all ears 😁

**Comment by apaldiwal** [comment]
> I think I like having them. I was almost thinking of, like, Pokemon cards (or what-have-you), and thinking about information that I could include in that direction. I could make it one of the filterable things, though.
> 
> On a related note, the cards will display how much xlm you earned as a prize for the quest, if you earned any. But, that stuff doesn't show up right away. If you're looking at them, and you change one of the filters, that information will show up in the re-render.
> 
> Probably something to do with the async fetch to the horizon endpoint.
> 
> Technically speaking, I'm not sure how to fix that. I'm looking into it, but if anyone knows off the top of their head, I'm all ears 😁

Maybe @Kanaye can help! He's my go to for all information related to Stellar. 😁

**Comment by ElliotFriend** [comment]
^ SAME!!! ^ 🤣

**Comment by Kanaye** [comment]
🤣 has nothing todo with stellar in this case.
So summoning a stellar-wizard doesn't help.
The good thing is, I'm a js-wizard too 🧙

The tl;dr is: you're setting the prize on the result asynchronously *after* you've called `setQuester` so the store will never know about the change in data and react can never render it.

I'll take a look in a few minutes 😉

**Comment by Kanaye** [comment]
https://github.com/ElliotFriend/sq-badge-checker/pull/1 fixes that bug 😉 
I rewrote the js a little, so it's totally up to you if you like it and want to accept the PR

**Comment by ElliotFriend** [comment]
Oh. My. God. 😳 I feel so honored!

Thanks for not only the information, but also for rewriting it! Amazing!!!! Thank you a thousand times!!

**Comment by Kanaye** [comment]
Youare welcome! 
Feel free to ask question about the code over on the PR if you've got some

**Comment by ElliotFriend** [comment]
I think, functionally speaking, I've nailed down all the pieces I've wanted to include. Still need to document the stuff, and clean up the repo, I think. But! I'm happy with how it's working :-)

I'm still not going to flip the emoji switch, though, until I have more comments/docs in the code.

**Comment by Kanaye** [comment]
I'll need to look at the codebase a little more when you think that you're ready with it.
The only things I've found UX-wise are:
- the "show proof + account (and maybe date when the verification was created?)"-thing from discord
- if you don't exactly hit the checkbox/toggle button, but the background, the overlay will close. Nothing major but a little akward UX wise.
![grafik](https://user-images.githubusercontent.com/5108989/128521025-122c8a33-7379-49b4-bf84-b430ce63a0db.png)


Otherwise I love the design + functionality ❤️

**Comment by ElliotFriend** [comment]
Yeah, that annoyed me about the toggles, too. I'll keep poking around with them and see if I can figure it out. Thanks!

**Comment by ElliotFriend** [comment]
The perfectionist inside me is screaming "no, not yet!" But, I think I'm ready for review 😁

**Comment by tyvdh** [comment]
@ElliotFriend 4703a99824f5fc9d55cb100ed60154a8ebf73d2ccd8979241ca252da5cc5bb2d
@Kanaye 48c202b03891ca3932244434330b75f3a6c33cd0fc995762f10b8b7f014dbb2e
@apaldiwal 652d9a583e8fa82609a3d76e6b15e180d39fbafb3e189eca489e6ad14f3c4804
