### ISSUE TITLE
🟣`create-bounties` Bounty for bounties! 

### ISSUE THREAD

**Issue by Smephite** [tyvdh/stellar-quest-bounties#45]
Create bounty for creating bounties... Bounty-ception!  
https://github.com/tyvdh/stellar-quest-bounties/pull/13 (Merged)
![bounty_small](https://user-images.githubusercontent.com/2955065/128030224-4dfe7c5a-b61d-41bb-bd2f-f08a1d2c0a17.png)

**Comment by tyvdh** [comment]
1ed505838977e6ae7f40dbe6dbee62e28e1194aadb29aac77d750510969b969c
