### ISSUE TITLE
🟣 `create-bounties` stellar-lab-improve-reorder-ux

### ISSUE THREAD

**Issue by hanseartic** [tyvdh/stellar-quest-bounties#48]
Add bounty to improve re-ordering operations in stellar laboratory's [transaction builder](https://laboratory.stellar.org/#txbuilder)

#8 (Merged)

**Comment by tyvdh** [comment]
d3a059a3f1c2396f43d458fbbaeb5cdbb8f942159b226bdf1e8d16bc5473f83e
