### ISSUE TITLE
stellar-lab-op-duplication.md

### ISSUE THREAD

**Issue by tyvdh** [tyvdh/stellar-quest-bounties#5]
https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/stellar-lab-op-duplication.md

**Comment by hanseartic** [comment]
started: https://github.com/stellar/laboratory/compare/master...hanseartic:bounty-no-5?expand=1

**Comment by hanseartic** [comment]
> started: https://github.com/stellar/laboratory/compare/master...hanseartic:bounty-no-5?expand=1
Ready from my point of view: https://github.com/hanseartic/stellar-laboratory

**Comment by tyvdh** [comment]
Closed via https://github.com/tyvdh/stellar-quest-bounties/issues/7
