### ISSUE TITLE
🔵 `create-bounties` merged-pull-requests

### ISSUE THREAD

**Issue by apaldiwal** [tyvdh/stellar-quest-bounties#50]
Added the following bounties, 

| Name | URL |
|:-----------:|:-----------:|
stellar-docs-code-snippet.md | [Link](https://github.com/tyvdh/stellar-quest-bounties/pull/1)
stellar-lab-op-duplication.md | [Link](https://github.com/tyvdh/stellar-quest-bounties/pull/3)
million-lumen-homepage.md | [Link](https://github.com/tyvdh/stellar-quest-bounties/pull/22)

**Comment by tyvdh** [comment]
0c48869b0afbca09f887f59f387b119254554cb75c5dcce388bf50c101e38220
