### ISSUE TITLE
stellar-docs-code-snippet.md

### ISSUE THREAD

**Issue by tyvdh** [tyvdh/stellar-quest-bounties#6]
https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/stellar-docs-code-snippet.md

**Comment by MatejMecka** [comment]
This PR Adds a Python Code Snippet for Channels: https://github.com/stellar/new-docs/pull/474

**Comment by apaldiwal** [comment]
This PR Adds a Python Code Snippet for Claimable Balance: [stellar/new-docs/pull/472](https://github.com/stellar/new-docs/pull/472)

**Comment by apaldiwal** [comment]
This PR Adds a Python Code Snippet for Clawbacks: [stellar/new-docs/pull/475](https://github.com/stellar/new-docs/pull/475)

**Comment by ralphilius** [comment]
This PR add Java code snippet to Channels https://github.com/stellar/new-docs/pull/476

**Comment by ralphilius** [comment]
This PR add Java code snippet to List Trade Aggregations API reference https://github.com/stellar/new-docs/pull/477

**Comment by apaldiwal** [comment]
This PR Adds a Python Code Snippet for Retrieve Fee Stats API Reference: [stellar/new-docs/pull/478](https://github.com/stellar/new-docs/pull/478)

**Comment by ralphilius** [comment]
This PR adds Java Code block to List Strict Send Payment Paths https://github.com/stellar/new-docs/pull/480
This PR adds Java Code block to List Strict Receive Payment Paths https://github.com/stellar/new-docs/pull/479

**Comment by tyvdh** [comment]
Once these start getting approved be sure and ping me so I know to issue the payouts. Also feel free to open new issues for yourselves tracking your own contributions to this bounty to ensure things aren't lost in this more discussion focused issue.

**Comment by tyvdh** [comment]
@MatejMecka 
@apaldiwal 
@ralphilius 

I'm going to close this issue as it doesn't track with the new bounty flow. Please open up individual issue tickets here tracking all of your own PRs in the docs repo. Sorry for the hassle but #beta.

If you're unfamiliar with the new bounty hunter flow please see https://github.com/tyvdh/stellar-quest-bounties/blob/main/README.md#flow-for-bounty-hunters

Feel free to ask any questions as you have them. Hoping the docs team will start merging these soon!
