### ISSUE TITLE
 review stellar-lab-op-duplication

### ISSUE THREAD

**Issue by hanseartic** [tyvdh/stellar-quest-bounties#7]
#5 is ready from my point of view: https://github.com/hanseartic/stellar-laboratory

![grafik](https://user-images.githubusercontent.com/1752217/127158684-7db18420-3cfd-49dd-bd55-d324aea3063a.png)

**Comment by Kanaye** [comment]
From a UI perspective: I'd love some margin between the "transaction" box and the buttons and between the buttons themselves.
![lab](https://user-images.githubusercontent.com/5108989/127161303-2d27e5cf-907e-40ce-b99d-0cead9a208a2.png)
Otherwise it looks good to me 😍

**Comment by apaldiwal** [comment]
Can we have a consistent shape for the buttons? Other than what Kanye mentioned, I'm perfectly fine with everything. Good job!

**Comment by hanseartic** [comment]
> Can we have a consistent shape for the buttons? Other than what Kanaye mentioned, I'm perfectly fine with everything. Good job!
> 
> ![image](https://user-images.githubusercontent.com/73634107/127165239-a0846c24-88b3-473b-ab84-50b598f611d0.png)

I think this way:
<img width="335" alt="grafik" src="https://user-images.githubusercontent.com/1752217/127228268-42c269a1-dbf5-47aa-85fa-450896c6f0d6.png">
it fits better to the order box above.
Whereas this:
<img width="580" alt="grafik" src="https://user-images.githubusercontent.com/1752217/127228406-e96b6095-26e8-4167-a9d1-75e89a6cb8a6.png">
matches the rest of the buttons. I am fine with both.

**Comment by hanseartic** [comment]
> From a UI perspective: I'd love some margin between the "transaction" box and the buttons and between the buttons themselves.
> ![lab](https://user-images.githubusercontent.com/5108989/127161303-2d27e5cf-907e-40ce-b99d-0cead9a208a2.png)
> Otherwise it looks good to me 😍

see https://github.com/tyvdh/stellar-quest-bounties/issues/7#issuecomment-887839997

**Comment by apaldiwal** [comment]
I agree with you on the first option. It looks much better!

**Comment by Kanaye** [comment]
I actually like the second variant more.
Yeah the first one looks better, but breaks the design, as all action-buttons are presented round and choices (e.g. `<input type="radio"/>`-ements are shown more like that , but I'm fine with both variants.

**Comment by hanseartic** [comment]
Thank you for the feedback. I agree, that from a consistency perspective on UX, the bubbly buttons should be used. But still the stacked buttons feel more space-economic to me.

**Comment by tyvdh** [comment]
So is this bounty considered complete? Passed by @Kanaye and @apaldiwal? How should we denote agent approval?

**Comment by hanseartic** [comment]
> So is this bounty considered complete? Passed by @Kanaye and @apaldiwal? How should we denote agent approval?

There was a suggestion here: https://github.com/tyvdh/stellar-quest-bounties/pull/17#issuecomment-888572429

**Comment by tyvdh** [comment]
> > So is this bounty considered complete? Passed by @Kanaye and @apaldiwal? How should we denote agent approval?
> 
> There was a suggestion here: [#17 (comment)](https://github.com/tyvdh/stellar-quest-bounties/pull/17#issuecomment-888572429).
> 
> But maybe better for later submissions? Specifically as this one has no PR against stellar-lab

Let's actually go ahead and submit a PR for this just to see what happens. But I think we should consider this bounty complete once we have a pending PR with Lab. It's probably not a bounty we want to be long lived anyway.

**Comment by hanseartic** [comment]
> But I think we should consider this bounty complete once we have a pending PR with Lab.

Could we agree on which design option to use before raising PR with LAB, please?

**Comment by tyvdh** [comment]
How/where should we link Stellar public keys? Should they just be linked somewhere in the review issue?

**Comment by tyvdh** [comment]
> > But I think we should consider this bounty complete once we have a pending PR with Lab.
> 
> Could we agree on which design option to use before raising PR with LAB, please?

This one. Lab team can make the final call if they even decide to accept it. I'd actually like to see icons used. A trash can and the clone icon, but its the functionality that matters most at this point.
![Screen Shot 2021-07-28 at 4 31 30 PM](https://user-images.githubusercontent.com/4383610/127391619-0af5e3de-7d1a-4de0-9956-1443fc4e5286.png)

**Comment by hanseartic** [comment]
> How/where should we link Stellar public keys? Should they just be linked somewhere in the review issue?

What about when filing the PR the feature branch should be named <PUBLIC_KEY>/<ISSUE_ID>?

**Comment by Kanaye** [comment]
> How/where should we link Stellar public keys? Should they just be linked somewhere in the review issue?

I guess that would be the easiest option for now. But for future it would be easier if we have some kind of "signup" process per hunter that catches that and maybe other stuff like tax-stuff (if we need that, no idea on US law) and so on.

**Comment by hanseartic** [comment]
https://github.com/tyvdh/stellar-quest-bounties/pull/19/files

**Comment by tyvdh** [comment]
Nice! 

@Kanaye 
@apaldiwal 

What about you guys? What address should I create a claimable balance for the agent credits?

**Comment by Kanaye** [comment]
Right, we should think about how Agents will sign up also 🤔 
For now I guess I'll just link it here: GA3KETGKS6Y53IMBZHTCFDVFMYOFVLAGPKIYQMSECBQ7425HPPKANAYE

**Comment by apaldiwal** [comment]
Oh, here's my public key: GCUIVEY5TAVRKBCHGVPFXXOZTRNCG7GWSEBFVYHPDN2YPJKGPAAAYE4N

**Comment by ralphilius** [comment]
> > How/where should we link Stellar public keys? Should they just be linked somewhere in the review issue?
> 
> I guess that would be the easiest option for now. But for future it would be easier if we have some kind of "signup" process per hunter that catches that and maybe other stuff like tax-stuff (if we need that, no idea on US law) and so on.

What about a config file in this repo? We should have <USERNAME>:<PUBLIC_KEY> for each line.

**Comment by tyvdh** [comment]
Payment made! Well claimable balance to be specific.
https://stellar.expert/explorer/public/tx/bbb4513f62ba56aee647890201a762e81ea4b9a1c3b2f7cbbd826cfb6dd149b7

Working on the credit payments now. Gotta think through those a little more.

**Comment by tyvdh** [comment]
@Kanaye and @apaldiwal I've got your claimable balances issued as well. Once you've setup trustlines I'll need to authorize them before you'll be able to claim I _think_.

https://stellar.expert/explorer/public/tx/94a368217dda86edc9ee215abe520da9b4861a9a2cf3c20948a546d6e3f1b384

Claimable balances with an auth required asset is an interesting scenario.

**Comment by Kanaye** [comment]
Yes, we need auth for that, just tested it as I wasn't sure ;) 
Or in other words: my trustline is setup.

**Comment by tyvdh** [comment]
```
AAAAAgAAAADaswFRJ8wh1zVzSaPvqVm2P0wbRxwYscQsEBrZGtR4xwAAAAACLoovAAAABQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAFQAAAACoipMdmCsVBEc1Xlvd2ZxaI3zWkQJa4O8bdYelRngADAAAAAIweDAwMDFmOWQwAAAAAAAA2rMBUSfMIdc1c0mj76lZtj9MG0ccGLHELBAa2RrUeMcAAAAAAAAAAQAAAAAAAAAVAAAAADaiTMqXsd2hgcnmIo6lZhxarAZ6kYgyRBBh/mune9QGAAAAAjB4MDAwMWY5ZDAAAAAAAADaswFRJ8wh1zVzSaPvqVm2P0wbRxwYscQsEBrZGtR4xwAAAAAAAAABAAAAAAAAAAEa1HjHAAAAQMxpqz38WQEFqIyK+hUJx9fGE4ow2+tAwM6pywQmV8FZ6g1jgn5IgBVSV3kZCvKr0/GwW2D9enNtsKHf2HQD2Ak=
```

Here's the transaction for authorizing the trustlines. You'll just need to wrap in a fee bump before submitting. Also don't run it until @apaldiwal has his trustline setup otherwise it will fail and the sequence number will become invalid and I'll need to regenerate it.

**Comment by apaldiwal** [comment]
I've set up my trustline! All set and good to go! :)

**Comment by Kanaye** [comment]
Check! Trustlines are authorized now. So you can claim your 2 `0x0001f9d0` 😄

**Comment by tyvdh** [comment]
Nice! We're good to close this Issue then yes?
