### ISSUE TITLE
🟣 `create-bounties` merged-pull-requests

### ISSUE THREAD

**Issue by ralphilius** [tyvdh/stellar-quest-bounties#79]
Name | PR
------|------
stellar-lab-albedo.md |https://github.com/tyvdh/stellar-quest-bounties/pull/9
stellar-lab-mobile.md |https://github.com/tyvdh/stellar-quest-bounties/pull/16

**Comment by hanseartic** [comment]
It looks to me, like the title could be changed to '🟣 `create-bounties` merged-pull-requests' as both PRs mentioned are already merged.

**Comment by ralphilius** [comment]
@hanseartic Updated. I saw other issue with the same code, so I think it's just for record keeping :)

**Comment by tyvdh** [comment]
f828f9e6bb8f38e3d5e03a5b01c312ce6d5ba9f9069632d059c4958c44f0c70e

Nice work!
