### ISSUE TITLE
Stellar accounts as a service

### ISSUE THREAD

**Issue by rahimklaber** [tyvdh/stellar-quest-bounties#87]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/create-bounties.md

### Mark your progress

- [x] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [ ] 🟣&nbsp; Review completed

### Provide relevant details

#86

**Comment by hanseartic** [comment]
This issue is exactly the use-case for #84: the progress was updated but not the issue-title.
