### ISSUE TITLE
Million Lumen homepage

### ISSUE THREAD

**Issue by rahimklaber** [tyvdh/stellar-quest-bounties#91]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/million-lumen-homepage.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

github repo : https://github.com/rahimklaber/MIllionLumenHomepage

I will be writing this in Kotlin/Js, so I'll have to create my own Kotlin type declarations of the Stellar SDK and albedo.

I 'm going to try to do this with only a front-end. If that doens't go well I'll add a back-end.

edit: hosted websited link : https://millionlumen.rahimklaber.me/

**Comment by rahimklaber** [comment]
I think I'll probably end up writing functions in js when I need the Stellar SDK and create definitions for those functions instead. Tried writing definitions for the SDK, but it got quite complicated at some point.

**Comment by rahimklaber** [comment]
You can now buy pixels as follows:
![image](https://user-images.githubusercontent.com/21971137/129124782-5ef5d51e-d86a-46ef-aadb-2004b1d128d5.png)

You create a transaction with a memo : "millionlumen" and 2 operations. The first is a payment for the total number of pixels and second is a manage data op with the name containing the ipfs hash of an image you want to add and the value is "[WIDTH]x[HEIGHT];[XCOORD];[YCOORD].

**Comment by tyvdh** [comment]
Made an attempt, seems it didn't work. 😢 
https://horizon-testnet.stellar.org/transactions/f539c68ab7de669828cf9275b9914ea4b2a8b93ca898a93f832f14784694c0e7

**Comment by rahimklaber** [comment]
> Made an attempt, seems it didn't work. 😢
> https://horizon-testnet.stellar.org/transactions/f539c68ab7de669828cf9275b9914ea4b2a8b93ca898a93f832f14784694c0e7

I will check it out, also I will put the address in text, forgot about that.

**Comment by rahimklaber** [comment]
> Made an attempt, seems it didn't work. 😢
> https://horizon-testnet.stellar.org/transactions/f539c68ab7de669828cf9275b9914ea4b2a8b93ca898a93f832f14784694c0e7

I think the problem is that you put the manage data op first.

**Comment by rahimklaber** [comment]
There seems to also be another problem where nothing renders unless you move your mouse over the canvas :(.

**Comment by rahimklaber** [comment]
It is now possible to buy pixels, currently there is a flat fee of 1 xlm per image. Right now there is now indication that it succeeded so you will have to check the console, if it was succesfull the submit tx response is logged.

https://millionlumen.rahimklaber.me/?a=buy

**Comment by hanseartic** [comment]
> You create a transaction with a memo : "millionlumen" and 2 operations. The first is a payment for the total number of pixels and second is a manage data op with the name containing the ipfs hash of an image you want to add and the value is "[WIDTH]x[HEIGHT];[XCOORD];[YCOORD]

The page actually uses three operations:
![grafik](https://user-images.githubusercontent.com/1752217/129851676-c5497f56-52be-47ec-a77f-70650a4be0d1.png)

**Comment by rahimklaber** [comment]
Yeah I changed it afterwards. The address is also differnet now.

**Comment by rahimklaber** [comment]
Thanks, for the feedback.

I will change the switch-to-testnet functionality to make it better.

I'll also add a Licence to the repo.

I think the project is pretty small and it should be easy to understand the code. Is there anything in particular you think is hard to understand?

As for the invisible pictures, yes it is intended.

**Comment by BlackBadPinguin** [comment]
No, not for me, but I think for people who are not used to coding some parts are not easy, however, from my standpoint, it's ready for a reward, even though I don't know if I'm permitted to give the approval.

**Comment by rahimklaber** [comment]
👍 I think the comments are fine then. As far as I remember you are allowed to approve. I think we discussed that for now anyone can review.

**Comment by tyvdh** [comment]
Can you get the testnet stood back up so I can review this? Thanks!

**Comment by rahimklaber** [comment]
@tyvdh It should be up again.

**Comment by tyvdh** [comment]
Purchased but the image isn't showing up. The space appears to be claimed but the image doesn't render in

**Comment by rahimklaber** [comment]
@tyvdh It take long to load initially. It should show up after a bit.

**Comment by tyvdh** [comment]
Nice! Got it

**Comment by tyvdh** [comment]
`05d842c817385f99f762d1b284cd763c326ef9ecbeeb0fa9d3ba9271c950533f`
