### ISSUE TITLE
Stellar docs code snippet

### ISSUE THREAD

**Issue by ElliotFriend** [tyvdh/stellar-quest-bounties#93]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/stellar-docs-code-snippet.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Horizon API Reference

| Name | Language |
| --- | --- |
| **Paths** | |
| List Strict Receive Payment Paths | [Python](/stellar/new-docs/pull/556) (Merged) |
| List Strict Send Payment Paths | [Python](/stellar/new-docs/pull/557) (Merged) |

**Comment by tyvdh** [comment]
`0b26d8ddb2111ede91df9ded9c851cd8decb5e5058ae9eb442b740d425a89ff1`
